CC = gcc
CFLAGS = -Wall -g -O2 -fPIE

TARGET := 17_myfile
SRCS := 17_myfile.c
OBJS := $(SRCS:.c=.o)

all: $(TARGET)

# TODO: 在这里添加你的代码
# I AM NOT DONE

clean:
	rm -f $(TARGET) $(OBJS)

.PHONY: all clean